# Generated by Django 4.2.4 on 2023-08-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('F', 'Free'), ('P', 'Pay')], default='F', max_length=1),
        ),
    ]
