# Generated by Django 4.2.4 on 2023-08-31 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_profile_course'),
        ('courses', '0002_course_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('coursep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_payment', to='courses.course')),
                ('profilep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_payment', to='accounts.profile')),
            ],
        ),
    ]
