# Generated by Django 4.2.4 on 2023-08-15 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_course_profile_course'),
        ('accounts', '0003_alter_profile_course'),
    ]

    operations = [
    ]
