# Generated by Django 4.2.4 on 2023-08-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_status'),
        ('accounts', '0004_merge_20230815_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='students_course', to='courses.course'),
        ),
    ]
